apiVersion: v2
appVersion: "v1.0.0"
home: https://github.com/al26p/k8s-as-helm
description: Helm Chart representing a single IngressClass Kubernetes API object
name: ingressclass
version: 1.0.0
icon: https://ameijer.github.io/k8s-as-helm/icon.png
maintainers:
  - name: al26p
    url: https://github.com/al26p
keywords:
- ingressClass
- api
- primitives
